language: python
sudo: true
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - mongodb

install:
  - bash setup_test.sh
script:
  # so to help eventual debug: knowing what exact versions are in use can be rather useful.
  - pip freeze
  # Code static analysis
  - pycodestyle --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_backend_import/*
  - pylint --rcfile=.pylintrc alignak_backend_import/*
  - pep257 --select=D300 alignak_backend_import
  # Code dynamic analysis
  - cd test
  # No code coverage tests
  - pytest test_*.py
  - cd ..
