language: python
sudo: true
python:
  - "2.7"
#  - "3.4"

services:
  - mongodb

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - bash setup_test.sh

script:
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_backend_import/*
  - pylint --rcfile=.pylintrc alignak_backend_import/*
  - pep257 --select=D300 alignak_backend_import
  - cd test
  # No coverage tests
  - nosetests -xv --nologcapture --process-restartworker --processes=1 --process-timeout=300 test*.py
  - cd ..
